let projects = [
  {
    id: "Patmus",
    category: "web",
    title: "Patmus",
    image: "/images/projects/tradepi.png",
    link: "https://www.patmus.co",
    description: `PI (Prediction Inteligence) is using AI to predict outcomes to Africas events.`,
  },
  {
    id: "statisense",
    category: "web",
    title: "Statisense",
    image: "/images/projects/statisense.png",
    link: "https://statisense.co/",
    description: `Statisense help businesses aggregate and convert complex customer data into simple visual insights using AI`,
  },
  {
    id: "airsmat",
    category: "web",
    title: "AirSmat",
    image: "/images/projects/airsmat.png",
    link: "https://airsmat.com",
    description: `AirSmat turns agricultural waste into scalable climate infrastructure across Africa — biochar-based fertiliser, verified carbon removal, and digital MRV.`,
  },
  {
    id: "440",
    category: "web",
    title: "440",
    image: "/images/projects/440.png",
    link: "https://www.get440.com",
    description: `440 helps African buyers import in bulk by sourcing directly from factories in China, the UK, and the US, with pooled orders and payments in naira.`,
  },
  {
    id: "clan",
    category: "web",
    title: "Clan africa",
    image: "/images/projects/clan.png",
    link: "https://creditclan.com",
    description: `Clan helps businesses & individuals offer point of need credit to consumers across Africa. Built with VueJS and Bootstrap`,
  },
  {
    id: "ileyah",
    category: "web",
    title: "ILEYAH",
    image: "/images/projects/ileyah.png",
    link: "https://ileyah.com/",
    description: `Statisense is helping millions of tenants pay their rent in easy, monthly subscriptions across Africa.`,
  },
];
export default projects;
